'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Check,Heart,LockKeyhole} from 'lucide-react';
import {Box,Saved,Goodie,ItemType,catalog,emptyBox} from '@/lib/catalog';
import {ShippingLabel} from './ShippingLabel';
import {TemplatePicker} from './TemplatePicker';
import {ItemGrid} from './ItemGrid';
import {Cart} from './Cart';
import {ItemEditor} from './ItemEditor';
import {useBoxTools} from './useBoxTools';
export const DRAFT_KEY='little-goodies-draft-v1';
export function Editor({initial,identity}:{initial?:Box;identity?:Saved}){
 const router=useRouter();const [box,setBox]=useState<Box>(initial||emptyBox);const [loaded,setLoaded]=useState(false);const [status,setStatus]=useState('Your box saves as you go');const [error,setError]=useState('');const [editing,setEditing]=useState<Goodie|null>(null);const [busy,setBusy]=useState(false);const saved=useRef<Saved|null>(identity||null);const latest=useRef(box);const queue=useRef<Promise<unknown>>(Promise.resolve());
 useBoxTools(box,setBox);
 useEffect(()=>{if(!initial){try{const raw=localStorage.getItem(DRAFT_KEY);if(raw){const d=JSON.parse(raw);if(d.box?.items){setBox(d.box);saved.current=d.saved||null;}}}catch{setStatus('Draft recovery unavailable on this browser');}}setLoaded(true);},[initial]);
 function persist(b:Box){const task=async()=>{setStatus('Saving your little things…');if(!saved.current){const r=await fetch('/api/packages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(!r.ok)throw Error(d.error);saved.current=d;}else{const r=await fetch(`/api/packages/${saved.current.id}`,{method:'PATCH',headers:{'Content-Type':'application/json','x-sender-token':saved.current.token},body:JSON.stringify(b)});const d=await r.json();if(!r.ok)throw Error(d.error);}try{localStorage.setItem(DRAFT_KEY,JSON.stringify({box:latest.current,saved:saved.current}));localStorage.setItem(`sender-${saved.current!.id}`,saved.current!.token);}catch{}setStatus('All your little things are saved');return saved.current!;};const pending=queue.current.catch(()=>{}).then(task);queue.current=pending;return pending;}
 useEffect(()=>{latest.current=box;if(!loaded)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({box,saved:saved.current}));}catch{setStatus('Browser storage is full — saving online');}if(!box.items.length&&!box.to&&!box.from&&!saved.current)return;const timer=setTimeout(()=>{persist(box).catch(e=>setStatus(`Not saved online: ${e.message}`));},900);return()=>clearTimeout(timer);},[box,loaded]);
 async function next(){if(!box.to.trim()||(!box.from.trim()&&!box.isAnonymous)){setError('Add who it’s for and who it’s from to finish your shipping label.');return;}setBusy(true);setError('');try{const s=await persist(box);router.push(`/send/${s.id}#${s.token}`);}catch(e){setError(e instanceof Error?e.message:'Could not save your box.');setBusy(false);}}
 function add(type:ItemType){setEditing(box.items.find(i=>i.type===type)||{type,qty:1,note:'',content:catalog.find(c=>c.type===type)!.defaultContent});}
 return <main className="create-page"><nav className="steps" aria-label="Progress"><span className="active"><b>1</b>Fill your box</span><i/><span><b>2</b>Wrap & send</span><i/><span><b>3</b>Make their day</span></nav><div className="page-intro"><span className="eyebrow">A SMALL GESTURE. A WHOLE LOT OF HEART.</span><h1>A little box.<br className="mobile-break"/> <em>A lot of love.</em><span className="heading-heart">♡</span></h1><p>A Little Box of Goodies — sent for sending a little care.</p></div><div className="workspace"><div className="packing-desk"><ShippingLabel box={box} onChange={setBox}/><div className="below-label"><label className="toggle-label"><input type="checkbox" checked={box.isAnonymous} onChange={e=>setBox({...box,isAnonymous:e.target.checked})}/><span className="switch"/>Send anonymously</label><span><LockKeyhole size={12}/> Just between you two</span></div><TemplatePicker box={box} onChange={setBox}/><div className="section-heading"><div><h2>Things to tuck inside</h2><p>A few of their favorite things. A little piece of you.</p></div><span>10 little possibilities</span></div><ItemGrid items={box.items} onAdd={add}/></div><div className="tray-column"><Cart items={box.items} onEdit={add} onQty={(type,delta)=>setBox({...box,items:box.items.map(i=>i.type===type?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0)})} onContinue={next} disabled={busy||!loaded}/><div className="handwritten cart-caption">a hug, in box form <Heart size={19}/></div><p className="save-status" role="status"><Check size={13}/>{status}</p>{error&&<p role="alert" className="error-message">{error}</p>}</div></div>{editing&&<ItemEditor item={editing} onClose={()=>setEditing(null)} onSave={item=>{setBox({...box,items:box.items.some(i=>i.type===item.type)?box.items.map(i=>i.type===item.type?item:i):[...box.items,item]});setEditing(null);}}/>}</main>;
}
