'use client';
import {useState} from 'react';
import {ExternalLink,Heart} from 'lucide-react';
import {Goodie} from '@/lib/catalog';
import {MiniGame} from './MiniGame';
function safeLink(value:string){try{const u=new URL(value);return u.protocol==='https:'?u:null;}catch{return null;}}
export function GoodieContent({item}:{item:Goodie}){const [hug,setHug]=useState(false);const [calm,setCalm]=useState(false);const u=safeLink(item.content);const spotify=u?.hostname==='open.spotify.com'&&/^\/(track|playlist|album)\/[A-Za-z0-9]+$/.test(u.pathname)?`https://open.spotify.com/embed${u.pathname}`:null;
 return <div className="goodie-content">{item.type==='quote'&&<blockquote>{item.content||'You are allowed to take your time.'}</blockquote>}{['song','playlist'].includes(item.type)&&(spotify?<iframe src={spotify} height="152" title={item.type==='song'?'Your song':'Your playlist'} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" referrerPolicy="no-referrer"/>:u?<a className="secondary" href={u.href} target="_blank" rel="noopener noreferrer">{item.type==='song'?'Play your song':'Open your playlist'}<ExternalLink size={14}/></a>:<p>A quiet soundtrack: take a moment to listen to the world around you.</p>)}{item.type==='photo'&&(item.content.startsWith('data:image/')?<img className="content-photo" src={item.content} alt={item.note||'A happy memory from your sender'}/>:<p>Picture your favorite day together. Keep it here for a moment. ♡</p>)}{item.type==='doodle'&&(item.content.startsWith('data:image/')?<img className="content-photo" src={item.content} alt={item.note||'A little doodle drawn just for you'}/>:<p className="handwritten">a tiny handwritten hello ♡</p>)}{item.type==='voice'&&(item.content.startsWith('data:audio/')?<audio controls src={item.content} aria-label="A voice note from your sender"/>:<p>A little whisper: you matter more than you know.</p>)}{item.type==='candy'&&<div className="candy-gift"><span aria-label={`${item.qty} candies`}>{'🍬'.repeat(item.qty)}</span><p>Something sweet, just for you.</p></div>}{item.type==='hug'&&<button className={`hug-button ${hug?'hugged':''}`} onClick={()=>setHug(!hug)}><Heart size={35}/>{hug?'Holding you a little longer. ♡':'Tap for a big, warm hug'}</button>}{item.type==='tea'&&<div className="calm"><button className="secondary" onClick={()=>setCalm(!calm)}>{calm?'Finish your quiet moment':'Take a breathing break'}</button>{calm&&<div className="breathing"><span/><p>Breathe in as it grows.<br/>Breathe out as it softens.</p></div>}</div>}{item.type==='game'&&<MiniGame/>}</div>;
}
