'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Eye,LockKeyhole,PackageCheck,Heart} from 'lucide-react';
import {PackageView,Saved,Box} from '@/lib/catalog';
import {ShippingLabel} from './ShippingLabel';
import {ShareSheet} from './ShareSheet';
import {Editor,DRAFT_KEY} from './Editor';
export function Sender({id,edit=false}:{id:string;edit?:boolean}){
 const [data,setData]=useState<PackageView|null>(null);const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [origin,setOrigin]=useState('');
 useEffect(()=>{setOrigin(location.origin);let t=decodeURIComponent(location.hash.slice(1));try{t=t||localStorage.getItem(`sender-${id}`)||'';if(t)localStorage.setItem(`sender-${id}`,t);}catch{}setToken(t);if(!t){setError('This page needs your private sender link. Open the link you saved when you made this box.');return;}let active=true;async function refresh(){try{const r=await fetch(`/api/packages/${id}`,{headers:{'x-sender-token':t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(active){setData(d);setError('');}}catch(e){if(active)setError((e as Error).message);}}refresh();const timer=setInterval(refresh,12000);return()=>{active=false;clearInterval(timer);};},[id]);
 async function publish(){if(!data)return;setBusy(true);setError('');try{const r=await fetch(`/api/packages/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json','x-sender-token':token},body:JSON.stringify({...data,publish:true})});const d=await r.json();if(!r.ok)throw Error(d.error);setData({...data,status:'sent'});try{const stored=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(stored?.saved?.id===id)localStorage.removeItem(DRAFT_KEY);}catch{}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function fork(){if(!data)return;setBusy(true);try{const r=await fetch('/api/packages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const s=await r.json();if(!r.ok)throw Error(s.error);localStorage.setItem(`sender-${s.id}`,s.token);location.assign(`/edit/${s.id}#${s.token}`);}catch(e){setError((e as Error).message);setBusy(false);}}
 if(!data)return <main className="center-page"><h1>{error?'A little key is missing.':'Finding your little box…'}</h1>{error&&<><p role="alert">{error}</p><Link className="primary" href="/">Make a new box →</Link></>}</main>;
 if(edit&&!data.openedAt)return <Editor initial={data} identity={{id,token}}/>;
 return <main className="send-page"><nav className="steps"><span><b>✓</b>Fill your box</span><i/><span className="active"><b>2</b>Wrap & send</span><i/><span><b>3</b>Make their day</span></nav><div className="page-intro"><span className="eyebrow">SEALED WITH A LITTLE LOVE</span><h1>{data.status==='sent'?'A little joy, ready to go.':'All tucked in. Almost there.'}</h1><p>{data.status==='sent'?'One small link. One very happy human.':'Give your box a last look, then send a little care their way.'}</p></div><div className="send-layout"><div><ShippingLabel box={data}/><div className="send-summary"><PackageCheck size={27}/><div><h3>{data.items.reduce((s,i)=>s+i.qty,0)} little goodies, handpicked by you</h3><p>Notes, little surprises, and plenty of love.</p></div></div><div className="send-toolbar"><Link href={`/preview/${id}#${token}`} className="secondary"><Eye size={17}/>Preview unboxing</Link>{!data.openedAt?<Link href={`/edit/${id}#${token}`} className="text-button"><ArrowLeft size={15}/>Edit package</Link>:<button className="text-button" disabled={busy} onClick={fork}>Make a new version <ArrowRight size={15}/></button>}</div><div className="status-card"><span className="eyebrow">DELIVERY DIARY</span><h2>{data.openedAt?`Opened by ${data.to} ♡`:'A little happiness is on its way.'}</h2><p>{data.openedAt?new Date(data.openedAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):data.status==='sent'?'Not opened yet. We’ll update this page when they unwrap it.':'Generate a link to get this delivery on its way.'}</p>{data.recipientReaction&&<div className="received-reaction">{data.recipientReaction}</div>}{data.recipientNote&&<blockquote>“{data.recipientNote}”</blockquote>}{data.openedAt&&!data.recipientReaction&&!data.recipientNote&&<small>No reply yet. Sometimes a smile is enough.</small>}</div></div><aside className="share-panel"><Heart size={27} strokeWidth={1.4}/><h2>{data.status==='sent'?'Special delivery!':'Ready for their doorstep?'}</h2><p>{data.status==='sent'?'Send them the link below. The surprise is waiting inside.':'Generate their personal link whenever your little box feels just right.'}</p>{data.status==='sent'?<ShareSheet url={`${origin}/p/${id}`}/>:<button className="primary full" onClick={publish} disabled={busy}>{busy?'Wrapping your box…':'Generate link'}<ArrowRight size={17}/></button>}<div className="private-section"><h3><LockKeyhole size={15}/>Just for you</h3><p>Keep this private link to edit your box and see when it’s opened. Send your recipient only the delivery link above.</p><ShareSheet url={`${origin}/send/${id}#${token}`} privateLink/></div>{error&&<p className="error-message" role="alert">{error}</p>}</aside></div></main>;
}
