import {chromium} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000');
await page.getByRole('heading',{name:'Things to tuck inside'}).waitFor();
mkdirSync('test-results',{recursive:true});
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await page.getByLabel('Recipient name').fill('Jamie');await page.getByLabel('Sender name',{exact:true}).fill('Alex');
await page.getByRole('button',{name:'Rough Day'}).click();
await page.getByRole('button',{name:'Customize Words to keep'}).click();
await page.getByLabel('Words you want them to keep').fill('You have got this.');
await page.getByRole('button',{name:'Tuck it inside'}).click();
await page.getByRole('button',{name:'Ready to wrap it up'}).click();
await page.waitForURL('**/send/**');
await page.getByRole('button',{name:'Generate link'}).click();
await page.getByRole('button',{name:'Share this box',exact:true}).waitFor();
await page.getByRole('link',{name:'Preview unboxing'}).click();
await page.getByRole('button',{name:'Tap to open your box',exact:true}).click();
await page.getByText('You have got this.',{exact:true}).waitFor();
await page.screenshot({path:'test-results/unboxing.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.goto('http://localhost:3000');
await page.getByRole('heading',{name:'Things to tuck inside'}).waitFor();
await page.screenshot({path:'test-results/mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw Error('Mobile layout overflows horizontally');
if(errors.length)throw Error(errors.join('\n'));
console.log('Browser checks passed: create, customize, generate, preview, unbox; desktop/mobile screenshots; no page errors or horizontal overflow.');
await browser.close();
